"""Fixture adapter for Etsy research - deterministic test data."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

from money_machine.integrations.etsy.interface import EtsyListingSearchResult, EtsyResearchAdapter


class FixtureEtsyAdapter(EtsyResearchAdapter):
    """
    Deterministic fixture adapter for Etsy research.

    Returns plausible young-and-fast shop listings across multiple niches.
    Never makes external API calls. Safe for all environments.
    """

    def __init__(self) -> None:
        """Initialize fixture data."""
        self._fixtures = self._build_fixture_data()

    async def search_listings(
        self, query: str, max_results: int = 50
    ) -> list[EtsyListingSearchResult]:
        """
        Return fixture listings matching the query.

        Args:
            query: Search phrase
            max_results: Maximum number of results

        Returns:
            Filtered fixture listings (up to max_results)
        """
        # Match fixtures by keyword overlap
        query_lower = query.lower().strip()

        # If query is empty, return all fixtures
        if not query_lower:
            return self._fixtures[:max_results]

        query_words = set(query_lower.split())

        results: list[EtsyListingSearchResult] = []
        for fixture in self._fixtures:
            title_words = set(fixture.title.lower().split())
            niche_words = set((fixture.identity_niche or "").lower().split())

            # Match if any query word appears in title or niche
            if query_words & (title_words | niche_words):
                results.append(fixture)

        return results[:max_results]

    def _build_fixture_data(self) -> list[EtsyListingSearchResult]:
        """Build deterministic fixture dataset with 40+ listings."""
        now = datetime.now(UTC)
        young_shop_age = now - timedelta(days=180)  # 6 months old
        fast_sales = 500  # Young shop with good traction

        return [
            # Planner/Productivity Niche (10 listings)
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1001",
                title="2024 Daily Planner Printable - Productivity Journal Template",
                price=Decimal("4.99"),
                anchor_price=Decimal("9.99"),
                currency="USD",
                shop_reference="PlannerProShop",
                shop_sales=fast_sales + 50,
                shop_opened_on=young_shop_age,
                identity_niche="productivity planner",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={"in_carts": "15+ people have this in their cart"},
                review_count=89,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1002",
                title="Weekly Goal Tracker Printable - Habit Tracker PDF",
                price=Decimal("3.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="HabitHeroDesigns",
                shop_sales=fast_sales - 100,
                shop_opened_on=young_shop_age + timedelta(days=30),
                identity_niche="habit tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=45,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1003",
                title="Budget Planner Template - Financial Goal Tracker Printable",
                price=Decimal("5.99"),
                anchor_price=Decimal("12.99"),
                currency="USD",
                shop_reference="MoneyMindsetCo",
                shop_sales=fast_sales + 200,
                shop_opened_on=young_shop_age - timedelta(days=20),
                identity_niche="budget planner",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"limited_time": "Sale ends in 6 hours"},
                review_count=156,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1004",
                title="Meal Prep Planner Printable - Weekly Menu Template",
                price=Decimal("4.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="HealthyHomeHub",
                shop_sales=fast_sales,
                shop_opened_on=young_shop_age + timedelta(days=15),
                identity_niche="meal planner",
                base_category="Kitchen & Dining",
                badges={"bestseller": False, "star_seller": False},
                urgency_signals={"in_carts": "8 people have this in their cart"},
                review_count=34,
                review_average=Decimal("4.6"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1005",
                title="Gratitude Journal Prompts - Daily Thankfulness Tracker",
                price=Decimal("2.99"),
                anchor_price=Decimal("6.99"),
                currency="USD",
                shop_reference="MindfulMomentsShop",
                shop_sales=fast_sales + 300,
                shop_opened_on=young_shop_age,
                identity_niche="gratitude journal",
                base_category="Books, Movies & Music",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"bestseller_badge": "Etsy's Pick"},
                review_count=201,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1006",
                title="Student Planner 2024 - College Assignment Tracker",
                price=Decimal("6.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="StudySuccessHub",
                shop_sales=fast_sales - 50,
                shop_opened_on=young_shop_age + timedelta(days=45),
                identity_niche="student planner",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=67,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1007",
                title="Password Tracker Printable - Secure Login Organizer",
                price=Decimal("3.49"),
                anchor_price=Decimal("7.99"),
                currency="USD",
                shop_reference="SecureLifePrints",
                shop_sales=fast_sales + 100,
                shop_opened_on=young_shop_age - timedelta(days=10),
                identity_niche="password organizer",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={"in_carts": "12+ people have this in their cart"},
                review_count=78,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1008",
                title="Workout Tracker Printable - Fitness Journal Template",
                price=Decimal("4.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="FitLifeDesigns",
                shop_sales=fast_sales + 150,
                shop_opened_on=young_shop_age + timedelta(days=60),
                identity_niche="workout tracker",
                base_category="Sports & Recreation",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=91,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1009",
                title="Desk Organizer Printable Labels - Office Storage System",
                price=Decimal("2.49"),
                anchor_price=Decimal("5.99"),
                currency="USD",
                shop_reference="OrganizedSpacesCo",
                shop_sales=fast_sales + 250,
                shop_opened_on=young_shop_age,
                identity_niche="desk organizer",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"limited_quantity": "Only 3 left"},
                review_count=134,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/1010",
                title="Travel Planner Printable - Vacation Itinerary Template",
                price=Decimal("5.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="WanderlustPrints",
                shop_sales=fast_sales - 80,
                shop_opened_on=young_shop_age + timedelta(days=75),
                identity_niche="travel planner",
                base_category="Bags & Purses",
                badges={"bestseller": False, "star_seller": False},
                urgency_signals={},
                review_count=42,
                review_average=Decimal("4.6"),
                observed_at=now,
            ),
            # Teacher Resources Niche (8 listings)
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2001",
                title="Teacher Appreciation Gift Tags - Thank You Cards Printable",
                price=Decimal("2.99"),
                anchor_price=Decimal("5.99"),
                currency="USD",
                shop_reference="TeacherTreasuresShop",
                shop_sales=fast_sales + 400,
                shop_opened_on=young_shop_age - timedelta(days=30),
                identity_niche="teacher appreciation",
                base_category="Paper & Party Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"trending": "Trending in Teacher Gifts"},
                review_count=267,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2002",
                title="Classroom Management Chart - Student Behavior Tracker",
                price=Decimal("3.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="ClassroomCornerCo",
                shop_sales=fast_sales + 180,
                shop_opened_on=young_shop_age + timedelta(days=20),
                identity_niche="classroom management",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=89,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2003",
                title="Lesson Plan Template - Weekly Teacher Planner Printable",
                price=Decimal("4.49"),
                anchor_price=Decimal("9.99"),
                currency="USD",
                shop_reference="EduPlanPro",
                shop_sales=fast_sales + 220,
                shop_opened_on=young_shop_age,
                identity_niche="lesson planner",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={"in_carts": "25+ people have this in their cart"},
                review_count=145,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2004",
                title="Student Awards Certificates - Achievement Recognition Printable",
                price=Decimal("2.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="AwardWinningTeachers",
                shop_sales=fast_sales + 90,
                shop_opened_on=young_shop_age + timedelta(days=40),
                identity_niche="student awards",
                base_category="Paper & Party Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=56,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2005",
                title="Back to School Labels - Classroom Organization Printable",
                price=Decimal("3.49"),
                anchor_price=Decimal("7.99"),
                currency="USD",
                shop_reference="SchoolSupplyCentral",
                shop_sales=fast_sales + 350,
                shop_opened_on=young_shop_age - timedelta(days=15),
                identity_niche="classroom organization",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"limited_time": "Flash sale - 50% off"},
                review_count=198,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2006",
                title="Alphabet Flashcards Printable - Phonics Learning Cards",
                price=Decimal("4.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="LearnAndGrowShop",
                shop_sales=fast_sales + 120,
                shop_opened_on=young_shop_age + timedelta(days=55),
                identity_niche="educational flashcards",
                base_category="Toys & Games",
                badges={"bestseller": False, "star_seller": False},
                urgency_signals={},
                review_count=73,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2007",
                title="Teacher Planner 2024 - Grade Book and Attendance Tracker",
                price=Decimal("6.99"),
                anchor_price=Decimal("14.99"),
                currency="USD",
                shop_reference="TeachAndThriveHub",
                shop_sales=fast_sales + 280,
                shop_opened_on=young_shop_age,
                identity_niche="teacher planner",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"bestseller_badge": "Best Teacher Tools"},
                review_count=212,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/2008",
                title="Reading Log Printable - Student Book Tracker Template",
                price=Decimal("2.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="BookwormClassroom",
                shop_sales=fast_sales - 70,
                shop_opened_on=young_shop_age + timedelta(days=85),
                identity_niche="reading log",
                base_category="Books, Movies & Music",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=38,
                review_average=Decimal("4.6"),
                observed_at=now,
            ),
            # Mindfulness/Wellness Niche (8 listings)
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3001",
                title="Mindfulness Journal Prompts - Daily Reflection Template",
                price=Decimal("3.99"),
                anchor_price=Decimal("8.99"),
                currency="USD",
                shop_reference="CalmMindDesigns",
                shop_sales=fast_sales + 310,
                shop_opened_on=young_shop_age - timedelta(days=25),
                identity_niche="mindfulness journal",
                base_category="Books, Movies & Music",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"in_carts": "18+ people have this in their cart"},
                review_count=187,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3002",
                title="Self Care Checklist Printable - Mental Health Tracker",
                price=Decimal("2.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="WellnessWarriorsCo",
                shop_sales=fast_sales + 140,
                shop_opened_on=young_shop_age + timedelta(days=35),
                identity_niche="self care tracker",
                base_category="Bath & Beauty",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=95,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3003",
                title="Mood Tracker Printable - Emotional Wellness Journal",
                price=Decimal("3.49"),
                anchor_price=Decimal("6.99"),
                currency="USD",
                shop_reference="MindfulMoodHub",
                shop_sales=fast_sales + 260,
                shop_opened_on=young_shop_age,
                identity_niche="mood tracker",
                base_category="Books, Movies & Music",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={"trending": "Popular this week"},
                review_count=176,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3004",
                title="Affirmation Cards Printable - Positive Mindset Daily Reminders",
                price=Decimal("4.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="PositiveVibesPrints",
                shop_sales=fast_sales + 190,
                shop_opened_on=young_shop_age + timedelta(days=50),
                identity_niche="affirmation cards",
                base_category="Paper & Party Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=112,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3005",
                title="Anxiety Relief Worksheets - Calm Down Strategies Printable",
                price=Decimal("5.99"),
                anchor_price=Decimal("11.99"),
                currency="USD",
                shop_reference="PeacefulPathDesigns",
                shop_sales=fast_sales + 85,
                shop_opened_on=young_shop_age + timedelta(days=65),
                identity_niche="anxiety relief",
                base_category="Books, Movies & Music",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"limited_time": "Sale ends tonight"},
                review_count=67,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3006",
                title="Sleep Tracker Printable - Restful Night Journal Template",
                price=Decimal("2.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="SleepWellHub",
                shop_sales=fast_sales - 60,
                shop_opened_on=young_shop_age + timedelta(days=90),
                identity_niche="sleep tracker",
                base_category="Health & Wellness",
                badges={"bestseller": False, "star_seller": False},
                urgency_signals={},
                review_count=41,
                review_average=Decimal("4.6"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3007",
                title="Meditation Guide Printable - Beginner's Mindfulness Practice",
                price=Decimal("4.99"),
                anchor_price=Decimal("9.99"),
                currency="USD",
                shop_reference="ZenLifePrints",
                shop_sales=fast_sales + 220,
                shop_opened_on=young_shop_age,
                identity_niche="meditation guide",
                base_category="Books, Movies & Music",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"bestseller_badge": "Bestseller in Meditation"},
                review_count=158,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/3008",
                title="Vision Board Template - Goal Setting Printable Worksheet",
                price=Decimal("3.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="DreamBigDesignsCo",
                shop_sales=fast_sales + 170,
                shop_opened_on=young_shop_age + timedelta(days=45),
                identity_niche="vision board",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={"in_carts": "14 people have this in their cart"},
                review_count=103,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            # Home Organization Niche (7 listings)
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4001",
                title="Pantry Labels Printable - Kitchen Organization System",
                price=Decimal("3.49"),
                anchor_price=Decimal("7.99"),
                currency="USD",
                shop_reference="OrganizedHomeHub",
                shop_sales=fast_sales + 380,
                shop_opened_on=young_shop_age - timedelta(days=20),
                identity_niche="pantry organization",
                base_category="Kitchen & Dining",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"trending": "Trending in Home Organization"},
                review_count=245,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4002",
                title="Cleaning Schedule Printable - Weekly Chore Checklist",
                price=Decimal("2.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="TidyHomeDesigns",
                shop_sales=fast_sales + 160,
                shop_opened_on=young_shop_age + timedelta(days=30),
                identity_niche="cleaning schedule",
                base_category="Home & Living",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=87,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4003",
                title="Moving Checklist Printable - Complete Relocation Planner",
                price=Decimal("4.99"),
                anchor_price=Decimal("10.99"),
                currency="USD",
                shop_reference="MoveMasterPrints",
                shop_sales=fast_sales - 90,
                shop_opened_on=young_shop_age + timedelta(days=70),
                identity_niche="moving checklist",
                base_category="Home & Living",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={"in_carts": "9 people have this in their cart"},
                review_count=52,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4004",
                title="Freezer Inventory Template - Food Storage Organization Sheet",
                price=Decimal("2.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="FreezerFriendlyHub",
                shop_sales=fast_sales + 110,
                shop_opened_on=young_shop_age + timedelta(days=55),
                identity_niche="freezer organization",
                base_category="Kitchen & Dining",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=64,
                review_average=Decimal("4.6"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4005",
                title="Home Maintenance Checklist - Seasonal Care Schedule",
                price=Decimal("3.99"),
                anchor_price=Decimal("8.99"),
                currency="USD",
                shop_reference="HomeCarePro",
                shop_sales=fast_sales + 200,
                shop_opened_on=young_shop_age,
                identity_niche="home maintenance",
                base_category="Home & Living",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"bestseller_badge": "Top Rated"},
                review_count=134,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4006",
                title="Spice Rack Labels - Kitchen Cabinet Organization Printable",
                price=Decimal("2.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="SpiceItUpDesigns",
                shop_sales=fast_sales + 290,
                shop_opened_on=young_shop_age - timedelta(days=10),
                identity_niche="spice organization",
                base_category="Kitchen & Dining",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={"in_carts": "11 people have this in their cart"},
                review_count=167,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/4007",
                title="Closet Organization Labels - Wardrobe System Printable",
                price=Decimal("3.49"),
                anchor_price=Decimal("7.99"),
                currency="USD",
                shop_reference="StyleAndStorageCo",
                shop_sales=fast_sales + 75,
                shop_opened_on=young_shop_age + timedelta(days=80),
                identity_niche="closet organization",
                base_category="Clothing",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={},
                review_count=49,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            # Financial Planning Niche (7 listings)
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5001",
                title="Debt Payoff Tracker - Financial Freedom Planner Printable",
                price=Decimal("4.99"),
                anchor_price=Decimal("11.99"),
                currency="USD",
                shop_reference="DebtFreeJourneyHub",
                shop_sales=fast_sales + 240,
                shop_opened_on=young_shop_age,
                identity_niche="debt tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"trending": "Trending in Finance"},
                review_count=189,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5002",
                title="Savings Challenge Printable - Money Saving Goal Tracker",
                price=Decimal("2.99"),
                anchor_price=None,
                currency="USD",
                shop_reference="SaveSmartDesigns",
                shop_sales=fast_sales + 320,
                shop_opened_on=young_shop_age - timedelta(days=15),
                identity_niche="savings tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={"in_carts": "22+ people have this in their cart"},
                review_count=203,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5003",
                title="Investment Tracker Spreadsheet - Portfolio Management Template",
                price=Decimal("5.99"),
                anchor_price=Decimal("12.99"),
                currency="USD",
                shop_reference="WealthBuilderPro",
                shop_sales=fast_sales - 100,
                shop_opened_on=young_shop_age + timedelta(days=95),
                identity_niche="investment tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": False},
                urgency_signals={},
                review_count=43,
                review_average=Decimal("4.6"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5004",
                title="Bill Payment Tracker - Monthly Expense Organizer Printable",
                price=Decimal("3.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="BillBuddyHub",
                shop_sales=fast_sales + 180,
                shop_opened_on=young_shop_age + timedelta(days=40),
                identity_niche="bill tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": True},
                urgency_signals={},
                review_count=98,
                review_average=Decimal("4.7"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5005",
                title="Net Worth Tracker Template - Financial Progress Worksheet",
                price=Decimal("4.49"),
                anchor_price=Decimal("9.99"),
                currency="USD",
                shop_reference="NetWorthNinja",
                shop_sales=fast_sales + 95,
                shop_opened_on=young_shop_age + timedelta(days=60),
                identity_niche="net worth tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"limited_time": "Weekend sale"},
                review_count=71,
                review_average=Decimal("4.8"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5006",
                title="Tax Deduction Tracker - Self-Employed Expense Log",
                price=Decimal("5.49"),
                anchor_price=None,
                currency="USD",
                shop_reference="TaxTimePro",
                shop_sales=fast_sales - 120,
                shop_opened_on=young_shop_age + timedelta(days=100),
                identity_niche="tax tracker",
                base_category="Office & School Supplies",
                badges={"bestseller": False, "star_seller": False},
                urgency_signals={},
                review_count=36,
                review_average=Decimal("4.5"),
                observed_at=now,
            ),
            EtsyListingSearchResult(
                source_reference="https://etsy.com/listing/5007",
                title="Emergency Fund Tracker - Financial Safety Net Planner",
                price=Decimal("3.99"),
                anchor_price=Decimal("8.99"),
                currency="USD",
                shop_reference="SecureSavingsHub",
                shop_sales=fast_sales + 210,
                shop_opened_on=young_shop_age + timedelta(days=25),
                identity_niche="emergency fund",
                base_category="Office & School Supplies",
                badges={"bestseller": True, "star_seller": True},
                urgency_signals={"in_carts": "16 people have this in their cart"},
                review_count=142,
                review_average=Decimal("4.9"),
                observed_at=now,
            ),
        ]
