"""first product slice"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_specs",
        sa.Column("product_spec_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_product_specs_hash"),
        sa.PrimaryKeyConstraint("product_spec_id"),
    )
    op.create_table(
        "research_packets",
        sa.Column("packet_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_research_packets_hash"),
        sa.PrimaryKeyConstraint("packet_id"),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("workflow_type", sa.Text(), nullable=False),
        sa.Column("packet_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('RESEARCHED', 'QUALIFIED', 'SPECIFIED', 'DEDUPE_PASSED', "
            "'BUILT', 'QA_PASSED', 'MERCHANDISED', 'PREFLIGHT_PASSED', "
            "'DRAFT_READY', 'INSUFFICIENT_EVIDENCE', 'REJECTED', 'FAILED')",
            name="ck_workflow_runs_state",
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_workflow_runs_hash"),
        sa.PrimaryKeyConstraint("workflow_run_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sa.Text(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("byte_count >= 0", name="ck_artifacts_byte_count"),
        sa.CheckConstraint("char_length(sha256) = 64", name="ck_artifacts_hash"),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.workflow_run_id"],
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
        sa.UniqueConstraint("workflow_run_id", "relative_path", name="uq_artifacts_workflow_path"),
    )
    op.create_index(
        "ix_artifacts_workflow_path",
        "artifacts",
        ["workflow_run_id", "relative_path"],
        unique=False,
    )
    op.create_table(
        "build_results",
        sa.Column("build_id", sa.Text(), nullable=False),
        sa.Column("product_spec_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_build_results_hash"),
        sa.ForeignKeyConstraint(
            ["product_spec_id"], ["product_specs.product_spec_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("build_id"),
    )
    op.create_table(
        "candidate_shortlists",
        sa.Column("shortlist_id", sa.Text(), nullable=False),
        sa.Column("packet_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_candidate_shortlists_hash"),
        sa.ForeignKeyConstraint(["packet_id"], ["research_packets.packet_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("shortlist_id"),
    )
    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.Text(), nullable=False),
        sa.Column("packet_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_candidates_hash"),
        sa.ForeignKeyConstraint(["packet_id"], ["research_packets.packet_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_table(
        "dedupe_results",
        sa.Column("dedupe_result_id", sa.Text(), nullable=False),
        sa.Column("product_spec_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_dedupe_results_hash"),
        sa.ForeignKeyConstraint(
            ["product_spec_id"], ["product_specs.product_spec_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("dedupe_result_id"),
    )
    op.create_table(
        "evidence_references",
        sa.Column("evidence_id", sa.Text(), nullable=False),
        sa.Column("packet_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_evidence_references_hash"),
        sa.ForeignKeyConstraint(["packet_id"], ["research_packets.packet_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("input_sha256", sa.Text(), nullable=False),
        sa.Column("retry_class", sa.Text(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_token", sa.Text(), nullable=True),
        sa.Column("leased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'READY', 'LEASED', 'RUNNING', 'RETRY_WAIT', "
            "'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name="ck_jobs_state",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_jobs_attempt_count"),
        sa.CheckConstraint("char_length(input_sha256) = 64", name="ck_jobs_input_hash"),
        sa.CheckConstraint(
            "lease_expires_at IS NULL OR leased_at IS NULL OR lease_expires_at > leased_at",
            name="ck_jobs_lease_expiry",
        ),
        sa.CheckConstraint(
            "(state IN ('LEASED', 'RUNNING') AND lease_owner IS NOT NULL "
            "AND lease_token IS NOT NULL AND leased_at IS NOT NULL "
            "AND lease_expires_at IS NOT NULL) OR "
            "(state NOT IN ('LEASED', 'RUNNING') AND lease_owner IS NULL "
            "AND lease_token IS NULL AND leased_at IS NULL AND lease_expires_at IS NULL)",
            name="ck_jobs_lease_binding",
        ),
        sa.CheckConstraint("max_attempts BETWEEN 1 AND 5", name="ck_jobs_max_attempts"),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.workflow_run_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_jobs_ready_queue",
        "jobs",
        ["state", "available_at", "created_at", "job_id"],
        unique=False,
    )
    op.create_index(
        "ix_jobs_workflow_order", "jobs", ["workflow_run_id", "created_at", "job_id"], unique=False
    )
    op.create_table(
        "research_observations",
        sa.Column("observation_id", sa.Text(), nullable=False),
        sa.Column("packet_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(payload_sha256) = 64", name="ck_research_observations_hash"
        ),
        sa.ForeignKeyConstraint(["packet_id"], ["research_packets.packet_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    op.create_table(
        "domain_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_domain_events_hash"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.workflow_run_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_domain_events_workflow_order",
        "domain_events",
        ["workflow_run_id", "occurred_at", "event_id"],
        unique=False,
    )
    op.create_table(
        "job_attempts",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("lease_token", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.CheckConstraint("attempt_number >= 1", name="ck_job_attempts_number"),
        sa.CheckConstraint(
            "state IN ('PENDING', 'READY', 'LEASED', 'RUNNING', 'RETRY_WAIT', "
            "'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name="ck_job_attempts_state",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "attempt_number"),
    )
    op.create_table(
        "job_dependencies",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_job_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("job_id <> depends_on_job_id", name="ck_job_dependencies_not_self"),
        sa.ForeignKeyConstraint(["depends_on_job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "depends_on_job_id"),
    )
    op.create_table(
        "listing_packages",
        sa.Column("listing_package_id", sa.Text(), nullable=False),
        sa.Column("product_spec_id", sa.Text(), nullable=False),
        sa.Column("build_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_listing_packages_hash"),
        sa.ForeignKeyConstraint(["build_id"], ["build_results.build_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_spec_id"], ["product_specs.product_spec_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("listing_package_id"),
    )
    op.create_table(
        "product_qa_results",
        sa.Column("product_qa_result_id", sa.Text(), nullable=False),
        sa.Column("build_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_product_qa_results_hash"),
        sa.ForeignKeyConstraint(["build_id"], ["build_results.build_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_qa_result_id"),
    )
    op.create_table(
        "qualification_scores",
        sa.Column("qualification_score_id", sa.Text(), nullable=False),
        sa.Column("candidate_id", sa.Text(), nullable=False),
        sa.Column("score_total", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_qualification_scores_hash"),
        sa.CheckConstraint("score_total BETWEEN 0 AND 40", name="ck_qualification_scores_score"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.candidate_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("qualification_score_id"),
    )
    op.create_table(
        "preflight_results",
        sa.Column("preflight_result_id", sa.Text(), nullable=False),
        sa.Column("listing_package_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(payload_sha256) = 64", name="ck_preflight_results_hash"),
        sa.ForeignKeyConstraint(
            ["listing_package_id"], ["listing_packages.listing_package_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("preflight_result_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("preflight_results")
    op.drop_table("qualification_scores")
    op.drop_table("product_qa_results")
    op.drop_table("listing_packages")
    op.drop_table("job_dependencies")
    op.drop_table("job_attempts")
    op.drop_index("ix_domain_events_workflow_order", table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_table("research_observations")
    op.drop_index("ix_jobs_workflow_order", table_name="jobs")
    op.drop_index("ix_jobs_ready_queue", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("evidence_references")
    op.drop_table("dedupe_results")
    op.drop_table("candidates")
    op.drop_table("candidate_shortlists")
    op.drop_table("build_results")
    op.drop_index("ix_artifacts_workflow_path", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_table("workflow_runs")
    op.drop_table("research_packets")
    op.drop_table("product_specs")
    # ### end Alembic commands ###
